Document: tas-wrapper
Title: Debian tas-wrapper Manual
Author: <insert document author here>
Abstract: This manual describes what tas-wrapper is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tas-wrapper/tas-wrapper.sgml.gz

Format: postscript
Files: /usr/share/doc/tas-wrapper/tas-wrapper.ps.gz

Format: text
Files: /usr/share/doc/tas-wrapper/tas-wrapper.text.gz

Format: HTML
Index: /usr/share/doc/tas-wrapper/html/index.html
Files: /usr/share/doc/tas-wrapper/html/*.html
